version: '3.8'
services: 
    ivs-db:
        image: mysql
        env_file: ./.env
        environment: 
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DOCKER_DB_ROOT_PASSWORD
        ports:
            - 3307:$DB_PORT
        security_opt:
            - seccomp:unconfined
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
    ivs-api:
        build:
            context: .
        env_file: ./.env
        command: npm start
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - 3010:$APP_PORT
        depends_on: 
            - ivs-db
        environment: 
            DOCKER_DB_HOST: ivs-db

volumes:
    mysql:
    mysql_config: